### ISSUE TITLE
Please support Raspberry Pi Model 3 B+

### ISSUE THREAD

**Issue by msnelling** [bendews/ansible-cloudflared#1]
On the Raspberry Pi 3B+, ansible_architecture returns as `armv7l`. The following line only checks for `arm`
https://github.com/bendews/ansible-cloudflared/blob/a9e753e9220b2d65e36aeb9294de062b1fdcfd9e/tasks/main.yml#L11

**Comment by msnelling** [comment]
It appears that just changing the check to `ansible_architecture is match '^arm.*'` does not work as `dpkg` complains with the error `Wrong architecture 'arm' -- Run dpkg --add-architecture to add it and update afterwards`.

However, downloading https://bin.equinox.io/c/VdrWdbjqyF/cloudflared-stable-linux-arm.tgz the extracted binary does indeed work.

**Comment by bendews** [comment]
@msnelling, great catch. Will look in to this over the weekend 😃
